### ISSUE TITLE
Establish metrics to measure the AR filing and goal to transition people to the new platform

### ISSUE THREAD

**Issue by trishreimer** [bcgov/business-ar#134]
Objective: transition corporations from the legacy to BR to reduce calls and to make it easier for people to login and use the system.

- [x] .# of corps to transition / accounts setup - starting with approximately 172K unique accounts that will need to be setup.

- [x] .#of AR's filed in the new BizReg - review activity report

- [ ] .#of people invited to file in the new BR but requested an access code to file in COLIN - need to look at activity report to review invited but did not file. Can also look at hotjar to see who started and dropped off - then look at why.

- [ ] .# of people who are requesting access codes today - this number should drop over time - and will demonstrate time savings as staff manually process these today. Anecdotally, business has 20 calls/day. (wrap code submitted)

- [ ] .#of calls related to AR filing (new wrap code submitted)

- [ ] .# of calls related to officers (new wrap code submitted)

AR Reminder:
- [ ] advised people to setup bcsc in advance. For UX - sent to 6 and advised them to do this...see how many people actually did. Data will help inform other comms on wording (e.g., stronger wording, formatting, etc.)

- [ ] in the app, can we count the # of times people click the basic or premium links?

stretch goal
- [ ] - Adding the AGM/no AGM/voting options will help people stay in compliance. Need to look into how this can be measured - what key results should we see?

**Comment by trishreimer** [comment]
Help Desk gets 600-700 calls  a month for the AR Reminder. Need to find out what these calls are about today.

**Comment by trishreimer** [comment]
Increase the number of people that need to onboard and transition from the legacy application to the new Business Registry platform. (includes account creation and affiliating a business.)
Reduced calls related to access codes
Improve the understanding of what BC Corporations need to do to stay in compliance regarding the annual general meetings.
With improvements on compliance and new data being captured, we are improving the data captured within the Registry and improving the overall data integrity. 
Improve the login credentials so we know who a person is when they login. This will help keep information secure and protected.
Reduced calls compared to other releases on account setup as the account setup flow was simplified.
Expanding the platform so it can be used by everyone with improved accessibility to government products and services (so reduced calls, if there are calls today)
Soon, we will reduce the number of AR reminders mailed so there is a a cost savings for government.

**Comment by vikas-gov** [comment]
- [ ] Created a dashboard to track eligible corps, invitations sent and filings till date
<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzkrQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c889d4b9cd1349294b072db75c475676af8dfc34/image.png" alt="image.png" />

- [ ] Need inputs for call center data for (new) wrap codes to create a similar metric to track inbound calls/traffic

**Comment by Maribeth-Wilson** [comment]
@nsmenon8890 - fyi

**Comment by vikas-gov** [comment]
Hi @sarahelz19, 
Request your help to get available call center data for (new) wrap codes AKA # of times ( New ) CC Wrap Codes is used by date/week  (Maximus, Corp. Support). 

Let me know if you have any questions. Thanks

**Comment by vikas-gov** [comment]
Hi @sarahelz19 , Could you please assist me with the data or connect me with the team that can support me with it? Thank you!

**Comment by sarahelz19** [comment]
> Hi @sarahelz19 , Could you please assist me with the data or connect me with the team that can support me with it? Thank you!

@vikas-gov I have established call codes with our support centers and will be asking for weekly data during stabilization. If you would like to schedule a meeting with me to discuss, my calendar is up to date and you can let me know if you require anything further

**Comment by vikas-gov** [comment]
After reviewing with @sarahelz19 , the plan is to engage and begin collecting data from the support center by the end of September 2024

**Comment by vikas-gov** [comment]
I inquired about the engagement expected to begin in late September, and the feedback received is that we will obtain the data for the wrap codes in a consumable format directly from Maximus/call centers.

**Comment by PCC199** [comment]
@nsmenon8890 @vikas-gov What is the disposition of this issue.

**Comment by trishreimer** [comment]
it can be closed. pls open new tix for any additional work.
