### ISSUE TITLE
Company changing name before attempting AR filing broke the link

### ISSUE THREAD

**Issue by dvdenis** [bcgov/business-ar#138]
Using BC0879839, I filed an effective immediate name change, and once that was completed, went to the link to file the annual report, but got the following error message, and was not able to access the annual report filing in BCROS:
<img width="700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTRQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89f5df7a7d50cbe2b122e5b06733ce544b04716e/image.png" alt="image.png" />

**Comment by deetz99** [comment]
@dvdenis This looks like a duplicated identifier, unfortunately generating the test data has made some duplicate businesses which causes an error. Could you please try another business and see if the issue still exists?

**Comment by deetz99** [comment]
@dvdenis Could you please confirm which name is the new one? Also do you remember if on the homepage, it displayed the correct name or not?

**Comment by dvdenis** [comment]
Hi there, the new name is AR SYSTEMS DESIGN INCORPORATED, which shows at the top of the filing, but the old name is showing in the company info section.
The new name is also showing correction in the COLIN system, if that's what you mean by the home page?
<img width="1004" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem9ZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0adf231c4c501c12b460cd696cf2ef68e3e1e091/image.png" alt="image.png" />

**Comment by deetz99** [comment]
@dvdenis Home page of the new annual report site, what the link in the test data sheet brings you to.

**Comment by dvdenis** [comment]
The screen shot at the top is what I was brought to, where it shows both names:
<img width="1173" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFlZQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d59b8922eccce41c6efb40fde55cbcdb5df48bf3/image.png" alt="image.png" />

**Comment by deetz99** [comment]
Okay thank you, will look into this.

**Comment by thorwolpert** [comment]
For MVP, we're _campaign_ driven, so we're pulling info from Colin and contacting the companies to file. The likelihood of this change in a campaign is probably very low.

Long term, if we make this the default AR we'll need to provide other pathways in, other than just the nanoid, and the change to address this would get taken up at that time.

**Comment by deetz99** [comment]
For now, I will make the change so the name is consistent on the annual report form. The name might still be the original on the index page if the invitation was sent prior to the name change

**Comment by dvdenis** [comment]
I have confirmed with the business that they DO NOT want the filing pulling in old names, it should reflect the name that is active in COLIN, regardless of what was in place when the AR link was sent out.  Please look at having this fixed.

**Comment by trishreimer** [comment]
@kris-daxiom has this been resolved? Can the business re-test?

**Comment by deetz99** [comment]
This should be fixed in https://github.com/bcgov/business-ar/pull/167

**Comment by deetz99** [comment]
Ready to test

**Comment by dvdenis** [comment]
Unable to test right now due to a blocker with creating and approving name requests.

**Comment by dvdenis** [comment]
Able to test, and can verify that the correct (new) name is pulled into the modern annual report filing.  Everything looks good now.

**Comment by deetz99** [comment]
Great thank you, closing this issue.
