### ISSUE TITLE
Determine help text implementation

### ISSUE THREAD

**Issue by deetz99** [bcgov/business-ar#147]
Ideas for Help Text Display:
- Modals
- Tooltips
- Popups
- New pages

UI Triggers for Help Text:
- Home page: button/link to open help text to guide users setting up BCSC if it hasn't been set up yet.
- Annual Report Page: button/link to open help text to assist businesses in remaining compliant with AGM date requirements.
- etc

Suggestions:
- Have 1 single page for all help text across app. Use full screen modal for mobile/tablet and new tab for desktop (switching tabs on mobile is a pain).
- Use markdown file/s for easy editing and maintenance of help content.
- If using a single help page, develop a solution to scroll to relevant sections based on different triggers. For example, clicking on "BCSC setup help" would open the help page and automatically scroll to the corresponding section.

**Comment by thorwolpert** [comment]
done
