### ISSUE TITLE
Finalize AGM question and answers.

### ISSUE THREAD

**Issue by deetz99** [bcgov/business-ar#148]
Finalize the wording for the AGM question and answers on the Annual Report page.

During the last check-in meeting, the revised text was not fully agreed upon and so was not included in this sprint. Please review the text and finalize a version for this sprint. Any major changes (beyond just altering the text) need to be decided as soon as possible. I've attached the latest Figma design for reference.
![Screenshot 2024-05-28 at 12 19 08 PM](https://github.com/bcgov/business-ar/assets/73151365/b95b2d1e-d1c4-4aaa-90ee-019760c4a0d3)

**Comment by deetz99** [comment]
@trishreimer @janisrogers

Could I suggest putting the additional fields below the radioGroup instead of inside? There is some extra work required to get the form to play nicely with additional fields inside the radioGroup, keeping the date fields/warning message outside the radioGroup will be more realistic to implement in time for external user testing. Something like this:
![Screenshot 2024-05-31 at 3 12 35 PM](https://github.com/bcgov/business-ar/assets/73151365/83410242-9909-4faf-b2da-311af163b645)

**Comment by trishreimer** [comment]
As noted in teams, I'm good with this design as we can adjust later once we get actual user feedback when we test with corporations.
This approach allows us to stay on track as well.
Thank you.

**Comment by deetz99** [comment]
Okay great, thank you.

**Comment by trishreimer** [comment]
I find this text a little confusing...I think we may need to make a minor tweak  but I'll need to review with the business to confirm. Can i just update this myself??

![image](https://github.com/bcgov/business-ar/assets/42844477/2ec90d55-5dcc-44ae-93e2-941595dab82f)

**Comment by deetz99** [comment]
If you're comfortable with updating text in the locales directory, yes. Just need to make sure the correct string is being updated as it's not as cut and dry as the content directory. If not then no problem, can create a new issue and I will take care of it.

**Comment by trishreimer** [comment]
i'm good with updating the file in the directory. Would you mind sending me the path or folder please (or link)?

**Comment by deetz99** [comment]
All translations are in the 'locales' directory found here:
[English](https://github.com/bcgov/business-ar/blob/main/web/site/locales/en-CA.ts)
and here
[French](https://github.com/bcgov/business-ar/blob/main/web/site/locales/fr-CA.ts).

The warning message above isn't implemented yet, working on that right now but I will comment here when it is in.

Please keep in mind any edits to the en-CA file will need to have the same key/value edited in the fr-CA file as well. Same goes for the content directory eg: content/en-CA/index, content/fr-CA/index.

Please let me know if you have any questions on how the translations are written.

**Comment by deetz99** [comment]
To update the compliance warning text, line 220 [English](https://github.com/bcgov/business-ar/blob/main/web/site/locales/en-CA.ts#L220), [French](https://github.com/bcgov/business-ar/blob/main/web/site/locales/fr-CA.ts#L220)

Please let me know if you have any questions.

**Comment by dvdenis** [comment]
I see the updated wording in the filing, but not sure if the second statement/option is worded properly?  It reads like it is missing something.  Should it be 'Our 20XX AGM is **yet** to be held'? or 'Our 20XX AGM has not been held **yet**'?
<img width="1281" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWhVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e1e455dd32de9c77fe00b0cac514677c9fd9a61/image.png" alt="image.png" />

**Comment by deetz99** [comment]
I had something similar previously that wasn't well received but this is easily editable by the OCM team as they see fit. All text for the app is mapped from the ./locales directory.

This particular line can be found here: [English](https://github.com/bcgov/business-ar/blob/main/web/site/locales/en-CA.ts#L215) and [French](https://github.com/bcgov/business-ar/blob/main/web/site/locales/fr-CA.ts#L215)
