### ISSUE TITLE
Get Admin Requirements

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/business-ar#152]
### invitations
- view invitations
- search invitations by:
  - partial name match
  - registration number (should be able to search with copy/paste from Colin, which doesn't have prefix)
  - email

### reports
- view filed reports 

### stretch
- Daily, weekly stats
  - return sets of data, daily summaries for a range of days, invitations sent, open, AR started, completed, accounts created, number of users filing an AR, number of unique users

**Comment by deetz99** [comment]
### invitations
- view invitations
- cancel invitation
- send/resend new invitation
- search invitations

### reports
- file on behalf of company
- edit filed reports
- delete filed reports
- view filed reports 
- search filed reports
