### ISSUE TITLE
Successfully filed the annual report for a company whose AR due date was December 29, 2024. Initially, COLIN threw an error stating that the AR couldn't be filed until December 29, but upon attempting in BCROS, the filing was completed successfully

### ISSUE THREAD

**Issue by nsmenon8890** [bcgov/business-ar#158]
I successfully filed the annual report for a company with an AR due date of December 29, 2024. COLIN initially threw an error, stating that the AR couldn't be filed until December 29. However, upon attempting it in BCROS, the filing was completed successfully.

After completing the filing, the AR filing status is updated in COLIN. 
             
<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjhmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64730a52a390a72b0e11796598f8e763f81a6625/image.png" alt="image.png" />

<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0FmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87aeb657f089ae2250ae76346f9b28a7938f3d41/image.png" alt="image.png" />

<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0lmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71026ea895fcbd1d1c549e757e62909becb828eb/image.png" alt="image.png" />

<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM01mQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b9244763f81be015595dadeaa94316583efbdd2/image.png" alt="image.png" />

<img width="597" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1FmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3176e95fdc63a0a706e7f0db3eebabc575a682a/image.png" alt="image.png" />

**Comment by trishreimer** [comment]
@deeI made some changes to the text in the UI here: https://github.com/bcgov/business-ar/tree/trishreimer-text-updates-1

**Comment by deetz99** [comment]
version: 1.4.0

**Comment by deetz99** [comment]
Ready to test

**Comment by nsmenon8890** [comment]
Tested and is working as expected,

<img width="1515" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWxEQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbad7961ccdfc33e5c95283e8b1c37c286c148bb/image.png" alt="image.png" />

**Comment by deetz99** [comment]
Great thank you, I will close this issue.
