### ISSUE TITLE
UI updates to the AGM information

### ISSUE THREAD

**Issue by andyyanggov** [bcgov/business-ar#165]
**Based on internal testing feedback:**

- [x] Add an explanation on why the AGM information is now collected.
- [x] Make it clear that the AGM information is for the current year’s AGM. We may want to consult senior examiners on the recommended terminology or phrasing.
- [x] Consider progressive disclosure (i.e., only show additional input fields based on the initial selection).
- [x] Add a warning or reminder about AGM compliance.

**Example of redesign (not reviewed):**

<img width="690" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelFsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11bc13ea21f28b645f8d5325bd41702d6a2e4460/AGM%20Info%20Redesign%20v2.png" alt="AGM Info Redesign v2.png" />

**Comment by deetz99** [comment]
This is completed in #148
