### ISSUE TITLE
UI updates to the Confirmation Page

### ISSUE THREAD

**Issue by andyyanggov** [bcgov/business-ar#166]
**Based on [internal testing feedback](https://docs.google.com/presentation/d/1m9z09FMBSqEQgyd5shgdPhf3MZj-WI51/edit?usp=sharing&rtpof=true&sd=true):**

- [ ] Add links to download the annual report and the receipt.
- [ ] Allow users to enter an email address if there is none associated with their account.

**Comment by deetz99** [comment]
The email address change, is this only to receive the receipt and filing copy? The next change will send the receipt/filing to the email associated with the invitation, instead of the user, business or account.

**Comment by andyyanggov** [comment]
Yes, for receiving the receipt and filing copy. Just curious, where is the email associated with the invitation pulled from?

**Comment by deetz99** [comment]
My mistake, the files will be sent to the email on the current account. If there is no email for the account then it will be sent to the invitation email.

**Comment by trishreimer** [comment]
Could we please prioritize this change? @deetz99

**Comment by deetz99** [comment]
@trishreimer 

Including 'Allow users to enter an email address if there is none associated with their account.'?
The report and receipt will be sent to the email from the invitation if there is no email associated with their account.

**Comment by deetz99** [comment]
@trishreimer 

So I have this in PR/DEV now, though only the receipt download is available at this time.
 
Currently, the report is not available until it is submitted to COLIN and reaches COMPLETED status. If the report fails in COLIN, there could be a difference between the filing and what we send to the user.
 
We could update it to return the filing before it has reached COMPLETED status but that might be a business question?

**Comment by thorwolpert** [comment]
no further changes requested, closing
