### ISSUE TITLE
Officers not required in BCROS - what are we doing once Corps is moved over - determine requirements

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#187]
- will not be required in new AR filing project
- will not be in new system
- see RAID tix [#251](https://app.zenhub.com/workspaces/raid--work-space-617c3d4cef313f001d715a7c/issues/gh/bcgov-registries/raid/251)

**Comment by trishreimer** [comment]
Can I close this? What is this for?

**Comment by trishreimer** [comment]
@Maribeth-Wilson
