### ISSUE TITLE
Implement ci/cd and hosting for Admin

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/business-ar#209]
- [x] Implement CI for Admin UI - web/admin
- [x] Implement CD for Admin UI
- [x] Implement hosting for Admin UI

Would this work:
  admin.annualreport.business.bcregistry.gov.bc.ca/

**Comment by pwei1018** [comment]
Done.

domain name will be:
https://dev.admin.annualreport.business.bcregistry.gov.bc.ca
https://test.admin.annualreport.business.bcregistry.gov.bc.ca
https://sandbox.admin.annualreport.business.bcregistry.gov.bc.ca
https://admin.annualreport.business.bcregistry.gov.bc.ca

**Comment by thorwolpert** [comment]
Verified and Completed
