### ISSUE TITLE
Corporations with future effective filings should not be able to file an AR

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/business-ar#223]
The current rules in COLIN, are that if a corporation has filed a future effective dated filing of any type, no further filings are allowed until that effective date is reached.
I filed an address change for BC0879834 on May 24, 2024, which meant that the address would not become effective until tomorrow (May 25, 2024), and it did display the newly updated address information, and it let me complete the filing.

This stop should be in effect for any future dated filings, ie. addresses, change of name, change of share structure.

Business has confirmed, if there are future effective dated filings in COLIN, then the AR filing should not be able to complete in BCROS until that filing effective date has happened.

**Comment by dvdenis** [comment]
@thorwolpert @trishreimer 
I was able to verify this with testing a future dated address change.
