### ISSUE TITLE
Change spacing for BN on initial page

### ISSUE THREAD

**Issue by deetz99** [bcgov/business-ar#229]
The BN should be formatted with a space between the BN9 and the other 6 characters.

example: 986395507BC0001
should be formatted as: 986395507 BC0001

**Comment by janisrogers** [comment]
The BN is not showing up on my test companies

**Comment by deetz99** [comment]
Not all test/dev business have a BN associated with them, so if theres no BN on the business, it won't be displayed.

**Comment by janisrogers** [comment]
Two of my test  companies (BC0025735 and BC0878280) have BNs in COLIN, but they don't show up in the AR filing.
<img width="754" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEcvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8bbf34851a1f5fed34e1a4cc9274990666e3e1c/image.png" alt="image.png" />

<img width="591" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE8vQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98840508a02130a34aadfead2f2e64ffed3d6753/image.png" alt="image.png" />

<img width="769" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFcvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa232e2b140be70ee9cd3959588392a44803834c/image.png" alt="image.png" />

<img width="637" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGUvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cea7e2085bb94b01184d15d7fe36b3dd78abfe7/image.png" alt="image.png" />

**Comment by deetz99** [comment]
Strange, they are both returning null in the requests.

<img width="770" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXkvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a73170ee2974356114e725c2415fd54ad602e0f5/Screenshot%202024-07-08%20at%2010.06.14%E2%80%AFAM.png" alt="Screenshot 2024-07-08 at 10.06.14 AM.png" />


<img width="692" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTIvQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0554ed503195a669a84d968675ce3836e138b108/Screenshot%202024-07-08%20at%2010.08.01%E2%80%AFAM.png" alt="Screenshot 2024-07-08 at 10.08.01 AM.png" />

**Comment by deetz99** [comment]
@janisrogers 

The test data was loaded from a spreadsheet that was missing the BN. We added them in now, please try again.

**Comment by janisrogers** [comment]
Looks good. 
![image](https://github.com/bcgov/business-ar/assets/55597599/028490da-224e-4910-85b1-f72a5fcee809)
