### ISSUE TITLE
Spike Choose email service

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/business-ar#235]
Determine what email service we'll use for delivering the notifications.
There are some new projects coming in by other teams that we might also want to dovetail into.

- [ ] GCNotify Bulk Email
GCNotify requires that emails are verified as significant _bounced_ emails degrades their service and email rating / reputation.
    - [ ] Email Verifier
      This would be to gather the cost of the verifier to use it as part of the cost comparison
- [ ] Gov't Email
The fully loaded cost of an gov't email, which includes IDir, Email, storage, etc.
- [ ] Sendgrid
Sendgrid is part of the in-app-notification service. It's _business_ account also includes email verification and bounced email management.

- [ ] RFC
Maybe a tiny RFC to capture the options and choices if we fall outside of what is currently in use, or add to the in-app-notification RFC to use its email services.

**Comment by ozamani9gh** [comment]
Here is my quick analysis.. perhaps @thorwolpert also can provide pros and cons.

GC Bulk Notifier:   Currently using for emails in BC Registries so assuming no extra cost

Email Verifier:

Emails | Price per email
-- | --
up to 10,000 | $0.008  - $80
up to 100,000 | $0.005 - $500
up to 250,000 | $0.004 - $1000
up to 1,000,000 | $0.003 - $3000

Government Email - no extra cost

SendGrid:

Three pricing options.    
Essentials package - $34.95/mo estimated*   100,000 emails a month
Pro - $1099/month      2,500,000 emails a month (Overkill in my humble opionion)
Premier - Custom - talk to SendGrid with actual expected numbers + contingency plan for extra emails.


I recommend SRE create RFC for pros/cons cost anaylsis if decision cannot be made with pricing above.

**Comment by thorwolpert** [comment]
project changes - so closing this
