### ISSUE TITLE
Liquidation check in colin

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/business-ar#244]
Add a check to the colin-api that can be used to show a business is in an ACTIVE state, but is also in the process of liquidation

**Comment by ozamani9gh** [comment]
This may or may not help

<img width="969" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGFLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce51fd907dee0688ec24094ba789340e8a904bcb/image.png" alt="image.png" />

**Comment by Maribeth-Wilson** [comment]
@thorwolpert - is this required before Sep 3rd?

**Comment by nsmenon8890** [comment]
Tested this case for company that are in Liquidation and Hanlun triggered the email for AR reminder and as expected I did not receive the email.
Test data used: BC0394191 , BC0373161 ,
