### ISSUE TITLE
Admin Freeze check in colin

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/business-ar#245]
Add a check to the colin-api that can be used to show a business is in an ACTIVE state, but is blocked due to an admin-freeze.

**Comment by ozamani9gh** [comment]
this may or may not be useful:

<img width="1030" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEtLQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--670abbd074c12b3fe57ace363d50e43fbd976321/image.png" alt="image.png" />

**Comment by Maribeth-Wilson** [comment]
@thorwolpert - is this required for Sep 3rd?

**Comment by ozamani9gh** [comment]
@Maribeth-Wilson can you confirm with business/home team which states are admin freeze.

From Steven:
corp_frozen_typ_cd has 3 values in corporation table. These values are null, 'C', and 'S'. Does null value mean a business is in an ACTIVE state? 'C' or 'S' means admin-freeze?
 
null	
C	COMPANY	COMPANY FROZEN
S	SELFSERV	SELF SERVED FROZEN

**Comment by nsmenon8890** [comment]
<img width="840" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3phQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16c474ae1df3763cd90d25b9594bb43a2bf224ee/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzNhQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6aa983166297f8e26573f8d5ac0e371b4be0682a/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMy9hQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--282eb5f91e22c9798965d1e7f7919faf4a739681/image.png" alt="image.png" />
