### ISSUE TITLE
Review text and translate & update to French 

### ISSUE THREAD

**Issue by trishreimer** [bcgov/business-ar#248]
*Update - please reach out to Genevieve next week.

She is going to help us translate our text from English to French.

Omid - could you please connect with her, walk her through the filing and show her how to make updates in github or if that does not work, could you please make the changes?

thanks.

**Comment by ozamani9gh** [comment]
Hanlun is working on ticket already this can be closed

**Comment by Maribeth-Wilson** [comment]
@ozamani9gh - do we still need someone from GDX to assist with translation or has this been resolved?

**Comment by trishreimer** [comment]
as discussed, Maribeth will be reaching out to gdx

**Comment by ozamani9gh** [comment]
@Maribeth-Wilson once Hanlun has pushed the French text up to dev/test then yes i would like someone to read it and make sure it makes sense.

**Comment by Maribeth-Wilson** [comment]
I reached out to Masha Kaur of GDX to see if they can assist. Will post response here.

**Comment by Maribeth-Wilson** [comment]
meeting with GDX on Jul 31st

**Comment by Maribeth-Wilson** [comment]
met with Sophie Poulin who works for SBC in Kelowna. Hanlun send her both english and french versions of the text to review. Should receive the week of Aug 5th.
