### ISSUE TITLE
Give users instructions for when addresses or directors are not correct

### ISSUE THREAD

**Issue by deetz99** [bcgov/business-ar#257]
Users need to be made aware of the fact that if the Office Addresses and the director information are incorrect, they should not proceed with the filing, and that they need to go to Corporate Online to update the information (and then come back) We also may want to let them know that they can update Director information and come back to file the AR right away, but that if they need to correct the address they will have to come back the next day.

Andy to come up with wording.

**Comment by deetz99** [comment]
@janisrogers @trishreimer 

Is a button/link to the help text enough for this requirement?

**Comment by trishreimer** [comment]
I would recommend screen text that says something like the text below. Andy - thoughts?

I don't actually think Office Addresses and (current) Directors should be title case either.

Please review the office addresses and current directors below. This information needs to be correct before you proceed. 

Then, could a little info icon be added that provides some help text. 

I'll draft some text here and post it below.

**Comment by trishreimer** [comment]
Help text wording:

Go to Corporate Online <link> to update your office addresses and directors, then come back here to file your annual report. If an office address was updated, you will need to wait until the next day to complete your annual report.

**Comment by deetz99** [comment]
@trishreimer 

Is this what you had in mind?

![Uploading Screenshot 2024-07-04 at 3.42.48 PM.png…]()

**Comment by trishreimer** [comment]
Is there a design standard for tool tip widths? If not, it may look a bit better if we increase the width of the tooltip overlap.
I'm also happy to let you decide and /or implement as is. We can always iterate later as the most important part is having the content there.
thanks

**Comment by thorwolpert** [comment]
Here's all the options you can do with tooltips -> https://ui.nuxt.com/components/tooltip

**Comment by deetz99** [comment]
As far as I know there is no hard set rule, though generally you wouldn't want to go too wide, so the user does not need to scan the whole page width while reading the tooltip info. The default max width is 320px but I can bump it up a bit, no problem.

**Comment by janisrogers** [comment]
Looks good.

**Comment by Maribeth-Wilson** [comment]
@janisrogers - can we close this ticket?

**Comment by janisrogers** [comment]
It was tested in test. I don't know if we have any verification in Prod, but it looked okay in test when I looked at it.
