### ISSUE TITLE
Give link in compliance warning 

### ISSUE THREAD

**Issue by deetz99** [bcgov/business-ar#258]
In the compliance warning we should give a link to help on compliance, or at least to the appropriate section of the act.

**Comment by deetz99** [comment]
@janisrogers @trishreimer 

Is a button/link to the help text enough for this requirement?

**Comment by trishreimer** [comment]
If I recall, this is to help the user understand their legislative requirements when they are filing their AR and when they are adding their AGM dates/no agm held, etc.  If we have a little (i) for on screen help text, could we add this link? 

Review the BC Corporations Act for more information. See section 182 or your annual general meeting requirements. 
https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/02057_00

**Comment by deetz99** [comment]
I'm not keen on using an (i) icon for the link, as this could be confusing with the other (i) which are tooltips.

I could do something like this:

![Screenshot 2024-07-04 at 3 22 04 PM](https://github.com/bcgov/business-ar/assets/73151365/09f79b01-a5f2-492f-9a4b-96e576946377)

Or something like this, which would open the current in-app help screen we have (the button text is easily changeable, just an idea)

![Screenshot 2024-07-04 at 3 28 15 PM](https://github.com/bcgov/business-ar/assets/73151365/3e2dd11f-e52d-4d29-8c22-66b7aa13c5df)

**Comment by deetz99** [comment]
Currently looks like this:

<img width="1032" alt="Screenshot 2024-07-04 at 3 38 56 PM" src="https://github.com/bcgov/business-ar/assets/73151365/a2aa3afc-9440-4d7d-be80-b4d2f02993be">

**Comment by trishreimer** [comment]
Ah, okay. I'm confusing help messages with tool tips. oops. (I may have done that on another tix as well)
My preference is the first mockup. 
Thank you

**Comment by deetz99** [comment]
Okay sounds good, thanks

**Comment by janisrogers** [comment]
@trishreimer  Can we change the wording on this to "A general meeting should be held every year. For more information review [Section 182 of the Business Corporations Act](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/02057_06#section182) to ensure that you are in compliance.

**Comment by magszymanski** [comment]
can we consider using "requirements" over "compliance"? Business uses "requirements" and that is a more user-friendly word. Thoughts on the below, @janisrogers ?

Generally, companies hold AGMs every year. View [Section 182 of the Business Corporations Act](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/02057_06#section182) to ensure you meet AGM requirements.

**Comment by janisrogers** [comment]
I see your point, and I think requirements is a friendlier word, but I think that might be too soft. I want to warn them so that they know that they have an obligation to be in compliance with the Act. I think using the scarier legal term might convey the urgency a bit more. What do you think?

**Comment by magszymanski** [comment]
I get that for sure! I worry more that there may be folks who don't know what that word means as it's jargon-y. I just checked the [gov corps page](https://www2.gov.bc.ca/gov/content/employment-business/business/managing-a-business/permits-licences/businesses-incorporated-companies/incorporated-companies) and they use "requirement" there as well. May want to keep it consistent? 

Let me know what you think my revision - I changed it somewhat from passive to active voice, but am happy to apply your earlier suggestion if that's what you folks land on:

Generally, companies hold AGMs every year. View [Section 182 of the Business Corporations Act](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/02057_06#section182) to ensure you meet AGM requirements.

![image](https://github.com/user-attachments/assets/d0838b71-162c-4abd-bcbd-6cf8d9ebd103)

**Comment by magszymanski** [comment]
Janis and I agreed on the below. Will include in PR later today.

Generally, companies hold AGMs every year. Review the [Business Corporations Act (Section 182)](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/02057_06#section182) to ensure you meet legislative requirements.

**Comment by Maribeth-Wilson** [comment]
@magszymanski - is this needed before Sep 3rd?

**Comment by magszymanski** [comment]
This has been done, closing tix.
