### ISSUE TITLE
Add button to "File another Annual Report" at the end of the filing, if one is due

### ISSUE THREAD

**Issue by trishreimer** [bcgov/business-ar#271]
As a business owner, if I have multiple outstanding AR's, I want to have the option to file another AR after I file my first AR, so that I can keep my business up to date.

**Comment by magszymanski** [comment]
Here is what displays once an outstanding AR is filed. Cannot file next one as there is a pending transaction in COLIN?

<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzFVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--26c6188baef1bf6e135c1618bc5d72d768a14e2f/image.png" alt="image.png" />

**Comment by Maribeth-Wilson** [comment]
@nsmenon8890 - fyi

**Comment by Maribeth-Wilson** [comment]
@ozamani9gh @EPortman - please provide an update on this tix as soon as possible. Thx

**Comment by EPortman** [comment]
@Maribeth-Wilson it is @hanlunBCRegistries who this ticket is assigned to.

@hanlunBCRegistries do you have an update on this ticket? If it is high priority and if I could potentially  help out in any way please let me know.

**Comment by hanlunBCRegistries** [comment]
@Maribeth-Wilson @EPortman I made some frontend changes yesterday but might need backend changes as well, will get back to this ticket once I have nano ids generation working in test.

**Comment by ozamani9gh** [comment]
@janisrogers @magszymanski are you able to give Ethan all the design specs for this ticket.

I’m a bit unclear on the specifics of this ticket. The goal is for users to file subsequent ARs until they’re up to date, but I’m not sure how the UI should reflect this.
 
When I complete an AR I get sent to the following screen:
<img width="698" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUdWQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8bc0416d8dcc422c1fa75d06c4e624b2f70b76d/image.png" alt="image.png" />

I'm assuming, and please correct me if I'm wrong, that the button to file the next year's AR should be placed on the above screen. If that's the case, I have a couple of questions about the UI:
 
1. Where should the button be positioned, and what should it look like?
2. What should the user see if the company doesn't have another filing to create?
  1. For example, should there be a message like, "You are up to date. The next filing will be available in `x months`."?
 
I've started working on the logic to handle this feature, including the necessary checks and actions upon button click. In the meantime, could we get someone from UI/UX to look into these details?
has context menu

**Comment by magszymanski** [comment]
I cannot open the image but I reckon it shows the confirmation screen, where I imagined this button going. "File 202X AR" and no button for up to date. I don't think we would need to give people an indication when their next one is - they will get an email reminder when it's time to file the next one.

I'll defer this to @janisrogers though as she has an understanding of what components should look like.

**Comment by ozamani9gh** [comment]
Waiting on Design before we can start

**Comment by jacqueline-williams-549** [comment]
**Designs**

[Login Screens](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2079-5402)
[Success Screens](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2248-10184)
[Flow](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2226-5790)

**Login Screen**

- Add year to screen title. eg: File your 2024 BC Annual Report
- Update titles for both sections (Login to BC Registries, No account?)
- Add list of annual reports
- - Add static text: Reports must be filed from oldest to newest.
- - When a report is overdue, it has a red background
- - When a report is not overdue (within 60 days of anniversary date), it has a grey background. Text is aligned to the text within overdue reports (but does not display the triangle warning icon)
- - The 'Login to File Report' button is disabled if it is not the oldest annual report (user can only file reports in chronological order)
- - If the user selects 'Login to File Report' the user is directed to BC Services Card Login (same as current state) 
- Read the overview button styling and text updates to "Annual Report Overview". Button links to the same place as current state.
- In the 'No account?' section, remove the bullet point
- Apply updates to mobile 
- - Primary button extends on mobile to fill the full width of the card

**Success Screen**
- Add year to title: "2023 Annual Report Complete"
- Add 'Your Receipt' title to first section
- Update styling of download receipt button
- Add 'File another Report' section
- - Add static text: Reports must be filed from oldest to newest.
- - When a report is overdue, it has a red background
- - When a report is not overdue (within 60 days of anniversary date), it has a grey background. Text is aligned to the text within overdue reports (but does not display the triangle warning icon)
- - The 'File Annual Report' button is disabled if it is not the oldest annual report (user can only file reports in chronological order)
- - Read the overview button styling and text updates to "Annual Report Overview". Button links to the same place as current state.
- Survey messaging is moved to the bottom section and external link icon has been added
- In bottom section there is a text update, "Service BC (SBC) Connect" has become "Service BC Connect"
- Apply updates to mobile
- - Primary button extends on mobile to fill the full width of the card

**Additional Styling updates**
- Font color
- Font Sizes

I will be adding the french translation for the screens today

**Comment by jacqueline-williams-549** [comment]
Can this ticket be tagged for ux assurance as well?

**Comment by ozamani9gh** [comment]
@Maribeth-Wilson this ticket is alot larger than initially scoped.   Ethan is going to create multiple tickets for this ticket that i will convert to Epic.

**Comment by Maribeth-Wilson** [comment]
Thanks @ozamani9gh
