### ISSUE TITLE
Set up meeting to coordinate what changes are required to reminder to encourage people to file

### ISSUE THREAD

**Issue by trishreimer** [bcgov/business-ar#283]
As discussed in our meeting today, could you please determine what changes are needed. 

might be best to recommend something then send the AR reminder out for feedback..

**Comment by trishreimer** [comment]
15 people decided to file in corporate online instead of in new AR flow. Two people called our staff to get access codes 

Recommend changes to the AR reminder to strengthen the wording and value.

Let's Focus on the what's in it for me. 

Also, please coordinate with @magszymanski to recommend changes to the UI.

**Comment by trishreimer** [comment]
It would also be great if we could survey these 15 folks to ask them why they did not file. My guess is BCSC.

**Comment by magszymanski** [comment]
I think the email intro could use a bit more context and like Trish said, more of the WIIFM. Have a look at the quick redo - we can iterate on it more on Tuesday: https://docs.google.com/document/d/1944k_HAL4d-Ql_CCTft26Q6aMMcfQAwSQyNABGnvV1E/edit

@LANHALL2  it's a great idea to reach out to these folks to see what made them file in COLIN. Maybe you and I can work on a draft email that we send out to them. Could be a survey too but I'd be interested in a quick call with them to really dive into what's going on. I'll set up a quick chat for us next week to discuss.

**Comment by magszymanski** [comment]
Ticket https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/293 for Design Team to review the AR reminder as they noted it can cause confusion. We have also reached out to all biz who filed in COLIN to learn about the reason. Results are in comments of same ticket. Closing this one.
