### ISSUE TITLE
schedule quick stand-up - tues/thurs - 5 mins w/Hanlun - support with issues/questions/blockers

### ISSUE THREAD

**Issue by trishreimer** [bcgov/business-ar#284]
Maribeth
- Would you mind setting up 2 - 5 mins standups - Tuesday/Thursday - with Hanlun - please include me so we can help with issues/blockers/questions. Omid as optional. 
- 

You may want to set up a new series of check-ins with the team/same time/day  - it's currently under Anshu's calendar.

**Comment by trishreimer** [comment]
Suggested ops/improvements process:
Improvements/changes:
I will move all items ready to be worked into the sprint backlog and these items will be ranked in order - feel free to pick any of these items up at any time Wang, Hanlun CITZ:EX
Every item in the sprint backlog and product backlog will be in a ranked order
Hanlun to reach out directly to team members directly with questions
Business
UX
Thor
feel free to use the AR filing teams chat (I'll add you).
As new items come in, they will need to be assessed to determine priority - Wilson, Maribeth CITZ:EX to determine impact and urgency, then assess priority (now, next, later).
If now, move to top of sprint backlog

**Comment by Maribeth-Wilson** [comment]
stand ups have been scheduled
