### ISSUE TITLE
Update third AGM information option as current option is incorrect

### ISSUE THREAD

**Issue by magszymanski** [bcgov/business-ar#285]
The third AGM option is inaccurate and is high priority to update. In Janis' absence, Mags is meeting with Andy to strategize wording on July 31 at 9:45 am. 

From Policy (Amber):

Based on the screenshots I received, there is an issue with the wording on the filing options regarding the holding of the AGM, specifically the third option. If this wording has been updated since these screenshots were current, then please let me know!

 <img width="576" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGNmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3362031bb1b21cee68799e1a3c7b2ffc8a8302e3/image.png" alt="image.png" />

Under the BCA it is not the board who is entitled to resolve whether an AGM will be held or not; it is the shareholders who are entitled to vote who will determine whether the unanimous resolution can be passed to do anything other than holding the AGM. The board of directors are not always shareholders, and if they are shareholders then they may not be a class of shareholders entitled to conduct voting. Either way, the wording on this option is incorrect and I suggest changing it. Furthermore, the BCA provides several options for resolution surrounding the AGM, not just the option to waive the meeting. The options are to unanimously defer, to consent to the business that is required to be conducted at the AGM, or to waive the holding of the AGM (this third option may also be retroactive to previous AGMs).

To avoid issues around misinforming companies, I suggest the wording be changed as soon as possible to something along the lines of “the shareholders entitled to vote at an annual general meeting have passed a unanimous resolution to either defer the AGM, waive the AGM, or consent to all of the business required to be transacted at the AGM”. Please note that simply stating “shareholders” will not be sufficient as there are many classes of shareholders of which only few may be those entitled to vote.

**Comment by thorwolpert** [comment]
The original text on the Annual Report form is "Waived, deemed to have been held"

**Comment by trishreimer** [comment]
Just adding my two cents...i don't even think we need to specify 'who' as it makes it over complicates this and there's information about referring to the Act for more information.
The original text on the AR form is simple and clear.

**Comment by andyyanggov** [comment]
"Our 2022 AGM is deferred, waived, or deemed to have been held."

Something like that?

**Comment by thorwolpert** [comment]
"Waived, deemed to have been held" was approved by legal, before Colin time

**Comment by magszymanski** [comment]
In response to Policy, I will share the below mock-up that uses the replaced option that Thor mentioned was approved by legal. As Policy's concern is misinforming companies, I recommend that we have the approved compliance warning disclaimer (ticket #258) show up not only for the 2nd option but also for this 3rd one. This way the user is informed to ensure they are compliant with what is stated about AGMs in section 182 without us listing all the details.

I'll be sending this to Amber shortly & getting a PR ready - unless anyone has any burning objections

<img width="1215" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2tqQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c3bdf2fbe4fba2ea13d3e95f1f3121fb557662b/image.png" alt="image.png" />
