### ISSUE TITLE
Requirement analysis: do we need to display or can we remove the certification section listing individuals' names on public outputs

### ISSUE THREAD

**Issue by magszymanski** [bcgov/business-ar#289]
I conducted a research session with a law firm on the AR reminder earlier this week and, unsurprisingly, received feedback that they’re uneasy about their employees’ names being listed when certifying that the information that is entered in a filing is correct. I say “unsurprising” as this is a recurring concern from our clients. 

What makes them most uneasy is that their personal name is publicly available via a Business Search, which can pose a risk to their safety – they are simply filing on behalf of the client, who they deem should be the once certifying the information is correct. Concern: what if the client is a bad actor or the employee is compromised by someone who is after the company. 

Trish raised a suggestion: what if we collect this data but don’t display it on the public-facing outputs, including AR filings, incorp applications, business summaries, etc. 

•	What does this look like in legacy? 
•	I just incorporated BC1144540 in  https://tst.corponline.gov.bc.ca/corporateonline/colin/static/colin/html/index.html and I see that the completing party is listed on the Incorp Application, but I’m unsure if this displays in the public outputs? 
•	And even if it does… aren’t law firms placing the name of their client who has signed the incorp application paper form to file the company in the system? In the Business Registry, there is no way to change the completing/submitting party, as the system pulls the name from the person who is logged in and filing. 
•	Do we have any options? Because if the above is accurate, law firm employees went from not being publicly displayed to have their name logged all over the register, available to the public for a mere $10 fee.

**Comment by Maribeth-Wilson** [comment]
@nsmenon8890 - can you please look into this? Thank you.

**Comment by magszymanski** [comment]
Closing tix as it's now on the OCM board (https://github.com/bcgov-registries/ocm-rte/issues/1773), icebox pipeline, awaiting leadership decision.
