### ISSUE TITLE
Update Header and Remove References to SBC Connect

### ISSUE THREAD

**Issue by hanlunBCRegistries** [bcgov/business-ar#290]
**Description:**
As per the request, we need to update the header in the application to remove "SBC Connect" and replace it with "BC Registries and Digital Services." 

**Tasks:**
1. Update the header text from "SBC Connect" to "BC Registries and Digital Services."

**Comment by hanlunBCRegistries** [comment]
PR created, code review needed

**Comment by magszymanski** [comment]
Whoops, I left this comment on PR 291 - so duplicating here:

"Service BC Connect" still appears on the Existing Account Found screen:

<img width="1555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1453dbd9ee44f86b96bf3ac61336119b0a274bb7/image.png" alt="image.png" />
