### ISSUE TITLE
Update review page for mobile

### ISSUE THREAD

**Issue by janisrogers** [bcgov/business-ar#292]
The current review page cuts off some of the address information and requires left/right scrolling of the tables showing Director's and Office addresses in order to see it all.
<img width="267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ZsQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5b6115640f31d5121e94ee4dc09b06d047fe4d2c/image.png" alt="image.png" />

A better user experience would be to change the table display for this breakpoint (only mobile, tablet is fine) to have the information stacked.
<img width="267" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL25sQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f642e380d97ec607e7e36cee2fec7ee9d76d0a55/image.png" alt="image.png" />

### Wireframes

The proposed design (labeled Proposed Design for Mobile) is here:
https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/Wireframe?node-id=1870-3512&t=8DBIImKMVOHGRiWv-0

**Comment by Maribeth-Wilson** [comment]
@janisrogers - an you please take a look at this tix? Thx

**Comment by nsmenon8890** [comment]
Tested the UI in test :  Please update as Registered office and Records office.

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0tjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b2bcf064fad5a310be0c8dfd65f2e86e0bd94a35/image.png" alt="image.png" />

**Comment by EPortman** [comment]
My mistake, I missed that part. I fixed this issue and it is now back in test environment.

**Comment by nsmenon8890** [comment]
Tested the UI in mobile and it looks good.
<img width="340" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGFwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fd9b0c63ab155e7654f89ef315a2d4bfb22ffa3/image.png" alt="image.png" />
