### ISSUE TITLE
AR Filing - Call for 1:1 Experience

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#294]
1:1 Experience:

- By EOD Friday, reach out to the 26 companies who received the new annual report reminder and find out why they filed in COLIN instead, analyze results – Sarah to draft email, then send through engagement mailbox no later than noon tomorrow
- Based on current UX feedback, please provide recommendation for improvements by EOD Friday., see tix #293

**Comment by Maribeth-Wilson** [comment]
Sarah has drafted (rough) a quick note requesting the participation in a 1:1 feedback for the online AR Filing (heading date August 7th) 
https://docs.google.com/document/d/1wtbTBiad-THykotDLY7hK4mvw7mOA4Md9L8ApDl_FQI/edit

**Comment by magszymanski** [comment]
Responses are located in the file that is mentioned by Maribeth above, last few pages. Closing tix.
