### ISSUE TITLE
Update AR Reminder email with new proposed text

### ISSUE THREAD

**Issue by magszymanski** [bcgov/business-ar#298]
@ozamani9gh @ozamani9 FYI:

@hanlunBCRegistries, the updated text is located in this [AR Reminder Doc](https://docs.google.com/document/d/1944k_HAL4d-Ql_CCTft26Q6aMMcfQAwSQyNABGnvV1E/edit). Please note that the Design Team is looking at this text at 1pm and a couple things may change - I will let you now by 1:30 what the outcome is, but feel free to review this doc now if you'd like.

**Comment by magszymanski** [comment]
@hanlunBCRegistries 
UX Design team suggested removing the first step of setting up a BC Services Card app since that step is covered when they go to the nanoID. Having the AR landing page as the starting point also gives the feeling of starting the AR process, which can increase adoption. 

I've updated the doc to reflect this and can chat more at the AR checkin. thanks.

**Comment by Maribeth-Wilson** [comment]
@hanlunBCRegistries - do you know if this has been pushed to prod?

**Comment by hanlunBCRegistries** [comment]
@Maribeth-Wilson Not yet since we cannot QA it yet, was trying to QA it yesterday but the job failed. Sent an email to Thor and check about it yesterday.
