### ISSUE TITLE
Language Switching Issue

### ISSUE THREAD

**Issue by hanlunBCRegistries** [bcgov/business-ar#304]
Description:

There's a problem where the index.1.md file in web/site/content/fr-CA/index/1.md does not change when switching the language from English to French. This issue persists even after trying to implement a local fix.

Steps to Reproduce:

Switch the language from English to French.
Observe that the index.1.md file does not update accordingly.
Proposed Solution:

Implement the following code to address the issue:
<img width="1201" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1JnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--137323f7313da8399a8acdcd902f9e106ba62e8f/image.png" alt="image.png" />

Current Status:

The above function fixes the issue locally, but after deployment, the page loads indefinitely.

**Comment by Maribeth-Wilson** [comment]
@hanlunBCRegistries - has this been fixed?

**Comment by hanlunBCRegistries** [comment]
@Maribeth-Wilson Not been fixed yet, I will work on it once the AR-reminder job works correctly

**Comment by ozamani9gh** [comment]
@nsmenon8890 ready to verify in test and then move to ready for release for tommorow
