### ISSUE TITLE
Revise AR Reminder link to state "File your annual report now."

### ISSUE THREAD

**Issue by magszymanski** [bcgov/business-ar#305]
Hanlun, please add the word “now” to the below in the AR reminder, to show: “File your annual report now”. It adds value by leaning into the psychology of user behavior to drive people to click on that and increase adoption of this initiative.
 
<img width="611" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0ozQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da7e37977978276d0a74d217ba6b6c990c73307a/image.png" alt="image.png" />

**Comment by Maribeth-Wilson** [comment]
Hi @hanlunBCRegistries can you please take a look at this today? Thx

**Comment by hanlunBCRegistries** [comment]
@Maribeth-Wilson @magszymanski working on it right now

**Comment by hanlunBCRegistries** [comment]
PR created
