### ISSUE TITLE
Create nano IDs for home team to test in COLIN - urgent

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#308]
- [ ] Home team requires more Nano IDs for testing in COLIN, they need these urgently to ensure we are ready for the Sep 3rd release 

- Assign to Omid's team, they should be able to do this. Same prep issue as always, test businesses in Colin are needed.

**Comment by ozamani9gh** [comment]
@hanlunBCRegistries how confident are you in creating Nano IDs in TEST to give to @nsmenon8890 and other testers when needed.

@rarmitag @EPortman also are you comfortable doing this as well as requested.

If all three of you are, lets close ticket

**Comment by hanlunBCRegistries** [comment]
I can create nano ids once we have necessary data from CTEST, also updated a new jupyter notebook to make the process more streamlined.https://github.com/bcgov/business-ar/blob/hanlun-notebook-new/ops/notebooks/Business-AR-cohort-7.ipynb
