### ISSUE TITLE
AR Filing - support for dev work

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#310]
In order to support Hanlun with his AR Filing work, the following is required:

- [ ] Determine who has the permissions to make modifications to the build. 
- [ ] Understand the specific permissions required for these changes. 
- [ ] Gain insight into how the AR-reminder job is set up and runs, as this knowledge is crucial for both development and providing operations support.

**Comment by trishreimer** [comment]
- the Ops team, including Hanlun should have permissions and access.
- if you don't have permissions, let us know what is needed
