### ISSUE TITLE
Validate nano IDs to ensure links work

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#312]
we need to ensure the nano ID links are working.

**Comment by thorwolpert** [comment]
What are you trying to test here?
We know, based on prior testing that the code works, so is the confirmation / verification of the configuration in prod?

**Comment by Maribeth-Wilson** [comment]
Once the nano IDs are available, we would like them to confirm they are all operational. @nsmenon8890 and the OCM team can do this.

**Comment by thorwolpert** [comment]
I think there some misunderstanding here.
The nanoids work and have been tested a lot.
They are just a token and you can either generate them for manual invites, or they get generated as part of the ar_reminder email.
The link in the AR_Reminder is already in production, and working.
If you want to do further testing (or as some others might call it, validation) in production, that can be done, if there's a goal / reason to do so?

**Comment by ozamani9gh** [comment]
Waiting for Nano Ids to be generated in PROD, and then click on links and confirm they work.
