### ISSUE TITLE
Develop 'Go Live' checklist

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#313]
The checklist will include all activities required to support this project, including:

**Product:**
- outstanding tickets
- testing in BCROS and in COLIN
- team able to create nano IDs
- nano ID testing complete
- what else needs to be added?

**Change management**
- all help desks advised and provided with quick quides and key messages
- staff and other BC Reg advised and provided with guides, etc. if needed
- email prepared for staff and help desks
- email sent to corps eligible to able to file the AR in BCROS
- updates made to external websites and staff info centre
- what else needs to be added?

Draft can be found [here](https://docs.google.com/spreadsheets/d/1EddTp37CYmpd9AABSQb54OV2UuZbqpNz/edit?usp=drive_link&ouid=100158666799678885533&rtpof=true&sd=true)

**Comment by trishreimer** [comment]
-	Why do you need to send email to corps eligible to file AR in BCROS (task id 8) – the batch job will send reminders automatically so no other emails should be required.
-	Are you going to use the teams chat for go live support? 
-	Are the comms/engagement plans up to date?
-	In addition to external site and Info centre, could we please ensure what’s new, SOFI and COLIN are updated with a message?
-	Maribeth – for post-implementation support, it may be helpful to remind teams that you are the lead and all work should be coordinated and prioritized by you.
-	Re: Go/no/go/ - can we remove the no, and just ensure we inspect and adapt our plans as needed?
