### ISSUE TITLE
Review of requirements for next release (potentially Sep 18)

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#317]
Omid, please review the list below:

Product backlog

- [ ] 288 – [update batch job](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/288) - We need the query to pull companies implemented in code

In Progress 

TESTING:

- [ ] 318 - [fix date issue - bug](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/318)

Ready for Release

DONE:
- [ ] 307 – [investigate – fix difference in effective date](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/307) - HOME TEAM CODE FIX

Closed
- [ ] #244 - Liquidation check in colin
Add a check to the colin-api that can be used to show a business is in an ACTIVE state, but is also in the process of liquidation
- [ ]#245 - Admin Freeze check in colin
Add a check to the colin-api that can be used to show a business is in an ACTIVE state, but is blocked due to an admin-freeze.
- [ ] 314 - [confirm AR reminder batch job – turn off AR prompt](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/314) 
- [ ] 319 - [Confirm dat will be deleted from AR_prompt in cprd](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/319) l
- [ ] 321 - [Ar reminder workflow](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/321)
- [ ] 292 – [update review page for mobile](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/292)
- [ ] 304 – [Language switching issue](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/304)
- [ ] 324 - [fix: Improper formatting of date in downloadable pdf receipt](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/324)
- [ ] 312 – [test nano IDs](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/312)

**Comment by ozamani9gh** [comment]
We ran production job yesterday, i am closing this ticket, and now we tackle tickets sprint by sprint
