### ISSUE TITLE
Fix date issue - bug - Last AR filing date is incorrect

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#318]

**Comment by Maribeth-Wilson** [comment]
@droberts27

**Comment by Maribeth-Wilson** [comment]
<img width="1631" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2VxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ea91b9c6977399667cb2b1253e70b5b3f2ba770/image.png" alt="image.png" />

**Comment by Maribeth-Wilson** [comment]
<img width="641" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3lxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ba51c10328be01a841200da9df50994ea8e9b2c/image.png" alt="image.png" />

**Comment by Maribeth-Wilson** [comment]
@ozamani9gh @hanlunBCRegistries - fyi above. Can you please take a look at this issue? Thx

**Comment by ozamani9gh** [comment]
I believe the code lives here:

api/src/business_ar_api/services/report_service.py

**Comment by EPortman** [comment]
**Reason this was occurring**
 - `Last AR Filed Date` comes from `founding_date`, it takes the month and date of this field and changes the year.
 - In Colin, founding date is stored in pacific local time but when they send it to Business AR they convert it to UTC (7 hours ahead)
 - We were sending this date back to Colin in UTC when it expected it in Pacific, causing the date to be one day ahead for any business with a founding time later than 5 pm. 
 
**Fix:**
 - Converted `founding_date` back to pacific time before sending to Colin.
 - This ensures the month and date of `recognition_date` (which comes from founding date) is always the same day as the month and date of `last_ar_filed_date`)
 
**To test this**
1. Find Business ARs with founding dates (recogniton date) that have a time after 5 pm pacific. 
2. Fill in the Business AR report
3. Run the following query against Colin (replace with the corp num in question):
```
select
to_char(e.event_timestmp,'yyyymmdd'  )        as event_date
,to_char(e.event_timestmp,'hh24:mi:ss')        as event_time
,to_char(f.effective_dt,'yyyymmdd hh24:mi:ss') as effective_dt
,c.corp_num
,f.event_id
,f.filing_typ_cd
,to_char(f.period_end_dt,'yyyymmdd')             as period_end_dt
,to_char(c.recognition_dts,'yyyymmdd')             as recognition_dt
,to_char(c.last_ar_filed_dt,'yyyymmdd')          as last_ar_filed_dt
,to_char(c.last_agm_date,'yyyymmdd')             as last_agm_date
,u.user_id
,u.last_nme
,u.email_addr
,f.access_cd
,p.event_id as payment
,c.send_ar_ind
from filing      f
    ,filing_user u
    ,event       e
    ,corporation c
    ,payment     p
where f.event_id=u.event_id
  and f.event_id=e.event_id
  and e.corp_num=c.corp_num
  and e.event_id=p.event_id(+)
  and filing_typ_cd='ANNBC'
  and user_id='BCOMPS'
  and (u.email_addr is null or c.last_agm_date is not null)
  and c.corp_num = 'INSERT CORP NUM HERE'
```
4. Confirm that `period_end_dt` and `last_ar_filed_dt` are the same dates.

**Comment by EPortman** [comment]
Deployed to Test and ready for QA.

**Comment by Maribeth-Wilson** [comment]
starting testing Sep 26 @nsmenon8890

**Comment by EPortman** [comment]
This is now in Prod.

**Comment by EPortman** [comment]
This PR was made in Colin to fix the `last_ar_filed_date` problem in Colin.
https://github.com/bcgov/lear/commit/82aec4b4e3dad31db03e25434332f2f79f3db225

It seems there is now a problem with the `period_end_date`. Since the 17th some of these fields are off. Likely a problem in Colin-API.

**Comment by ozamani9gh** [comment]
@EPortman lets create a new ticket related to period_end_date

**Comment by EPortman** [comment]
This was the query I have been using to verify data after completing ARs.
```
select
    to_char(e.event_timestmp,'yyyymmdd')        as event_date,
    to_char(e.event_timestmp,'hh24:mi:ss')      as event_time,
    c.corp_num,
    f.filing_typ_cd,
    to_char(c.recognition_dts,'yyyymmdd hh24:mi:ss')       as recognition_dt,
    to_char(f.period_end_dt,'yyyymmdd')         as period_end_dt,
    to_char(c.last_ar_filed_dt,'yyyymmdd')      as last_ar_filed_dt
from filing      f,
     event       e,
     corporation c
where 
  f.event_id = e.event_id
  and e.corp_num = c.corp_num
  and c.corp_num = '0108130'
order by e.event_timestmp desc;
```

Here is a company that had problems before and after the fix (notice in the recent ones the `period_end_date` has a month and day that matches the `recognition_date`.
<img width="759" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU5tQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a39bfe7db54290c160ea3912696f6a6c5da2e30/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
Testing result:

Before filing AR:

<img width="1220" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTl3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8425720c153f1fdbb81b10d72c43e96eae77bc73/image.png" alt="image.png" />

<img width="1040" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkJ3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d4ec3c45a1e40f43e4a38a2bf9939724ab65e6e/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
After filing : 

<img width="1327" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE53Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e2317adfa1ce6b908f407eaca0120b9452268f9/image.png" alt="image.png" />


<img width="1338" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFp3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d40aae95a70056befae6491cfafabfed1a3e3dc/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="994" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHh3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--100a9d8f801c4abe849a9cce815b0789529f260e/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
Tested for BC0873502

<img width="1060" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1J3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--377cff53d1a7088937f1d366fb3b10fb20dde0f7/image.png" alt="image.png" />

<img width="1323" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1Z3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f261c1c6071e654f2cc54d4fdde859972f75698/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
Tested for BC0821498:
<img width="1047" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzl3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2910a3911f44fc1cd465a91e95a74c5d2513d2d2/image.png" alt="image.png" />

<img width="1209" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0J3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2883e1039f3104d81f9a5365585c2a62b14ae32a/image.png" alt="image.png" />
