### ISSUE TITLE
Confirm that data will be deleted from AR_prompt in cprd when a user files their annual report when using the AR Filing flow

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#319]
After someone has filed their annual report, Business A/R will need to call a lear endpoint to query the corp_num in AR_PROMPT Table and delete the record

SQL> select * from ar_prompt where corp_num='0754041';
 
CORP_NUM   ACCESS_CD PERIOD_END DD_CORP_NU EMAILED_PROMPT_TO
---------- --------- ---------- ---------- -------------------------
0754041    139620512 2016-04-05            michael.kagis@gov.bc.ca
0754041    143514347 2017-04-05            melissa.stanton@gov.bc.ca

**Comment by ozamani9gh** [comment]
@vikas-gov  we might need @vysakh-menon-aot  for this as well, but we can discuss tommorow or monday.
