### ISSUE TITLE
fix: Improper formatting of date in downloadable pdf receipt

### ISSUE THREAD

**Issue by EPortman** [bcgov/business-ar#324]
After paying for an AR, and pressing the download receipt button. In the PDF that is downloaded, the date/time is not formatted correctly. 

<img width="709" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2F1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b79bad2990b17d2ba265aaf1289b22fbf4c07b13/image.png" alt="image.png" />

**Comment by ozamani9gh** [comment]
this is the format we are proposing to fix above error. please confirm if this is correct or another format

"September 03, 2024, 02:42 PM PDT"

**Comment by nsmenon8890** [comment]
Current format in Colin:
<img width="859" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0N3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--708487c3283d958d39a6e1a783943a7f902b3962/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
Please have the same format.

**Comment by Maribeth-Wilson** [comment]
@ozamani9gh - please see Neeraja's comment above, please proceed with this change

**Comment by EPortman** [comment]
New Format:
<img width="745" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3UwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--252ee32aebf6b604de6b9092a3d624b1105448ce/image.png" alt="image.png" />

**Comment by ozamani9gh** [comment]
@nsmenon8890 please test this ticket.

**Comment by nsmenon8890** [comment]
Testing is completed and dates are displayed in the correct format.

<img width="1039" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK20wQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--467d4008913c5703e143935cf7cc890e031fb683/image.png" alt="image.png" />

**Comment by EPortman** [comment]
Thank you, @nsmenon8890
