### ISSUE TITLE
AR Filing Corrections - for review by team 

### ISSUE THREAD

**Issue by sarahelz19** [bcgov/business-ar#327]
A Request came in via BC Registries Engagement mailbox asking the following: 
1) If I make a mistake on my AR filing - can I submit a correction via Form 47?
2) If I submit a form 47 does the $20 fee apply 

Summary of Policy Response: 
All filings must have the ability for a correction 
The $20 Fee must apply to all correction requests
The correction must be indicated as part of the filing ledger 

Policy: 

> From a policy perspective, my interpretation of the legislation is that yes this would require a form 47 and the legislated fee of $20 to be paid. Please note there is indeed a legislated fee in the BCA for filing any record for which there is no fee indicated in the schedule (line 15). This “catchall” fee is captured in the various acts we administer, sometimes with a differing dollar amount depending on the act. It is exceedingly rare that we will file anything without payment of a legislated fee – even a court order filed on a company requires the $20 fee to be paid.
> 
> The annual report is required under section 51 of the BCA. The section states that the annual report is to be filed “in the form established by the registrar”. Changing this form to include more information, such as the AGM information, is, in my interpretation, in line with this description. The annual report is then filed onto the ledger of the company. I presume that the outputs would reflect the new AGM information we are requiring, but could someone please confirm that for me?
> 
> Section 414 deals with corrections in any register kept by the registrar. This section requires that the registrar “is satisfied that an error or omission exists and as to the true facts that ought to have been incorporated into the register”. The correction must be shown in the ledger as a correction with the date and time of the correction noted. This has always been done by a form 47 filing which takes information from the applicant to support the registrar making the correction. Filing a form 47 would require the legislated fee in the schedule. Following this well-established corrections flow will be important especially if there are outputs that demonstrate incorrect information about the AGM date.
> 
> An additional word of caution – section 414 has long standing policies around the correction of information due to its wide interpretation applications to every registry we administer. Without consistent policy we have always run the risk of confusing the public around which corrections can be made, how they are made, and the resulting documents that may arise out of a correction. Any changes to policies around corrections should be carefully considered, perhaps with legal counsel weighing in. 
> 
> This is my interpretation of the legislation, and you may wish to seek legal advice on this matter. Elizabeth, please let me know if you’d like me to draft something up.
> 
> 
>

**Comment by Maribeth-Wilson** [comment]
@nsmenon8890 - can you please take a look at this tix and advise what is needed? Thank you

**Comment by sarahelz19** [comment]
@Maribeth-Wilson @nsmenon8890 this is an old ticket. Kaine stated we would not collect a fee for Officer Corrections for the AR Filing
