### ISSUE TITLE
INVESTIGATION:  Duplicated AR entry created in COLIN by Business AR filing

### ISSUE THREAD

**Issue by Mihai-QuickSilverDev** [bcgov/business-ar#328]
See 
https://sbc-registries.atlassian.net/browse/ITOPS-137836 for details.

These two ARs came from the modernized application.  Here is the CPRD data.  Note that the filing_user.user_id is BCOMPS.

EVENT_ID CORP_NUM   EVENT_TYP_ event timestamp   trigger date      effective_dt      PERIOD_END AGM_DATE   FILIN filing_type                                        WITHDRAWN_EVENT_ID OD NR_NUM     filing_user role_typ_cd filing_user user_id

-------- ---------- ---------- ----------------- ----------------- ----------------- ---------- ---------- ----- -------------------------------------------------- ------------------ -- ---------- ----------------------- -------------------

19372692 1376383    FILE       20240828 12:46:14                   20240828 12:42:34 2024-08-24            ANNBC File an Annual Report - BC Company                                    F                                     BCOMPS

19372685 1376383    FILE       20240828 12:44:13                   20240828 12:42:34 2024-08-24            ANNBC File an Annual Report - BC Company                                    F                                     BCOMPS

<img width="1467" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEcxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0ffa6e3049ae590e7e5c1b19b7a931ca63a7c2e/image-20240905-154922.png" alt="image-20240905-154922.png" />

It was part of the August 19, 2024 target group:

SQL> select * from set_ar_to_no where corp_num='1376383';

CORP_NUM   P UPDATE_DAT

---------- - ----------

1376383    Y 2024-08-19

As expected, there are no payments in CP{RD for the two modern ARs:

SQL> select * from payment where event_id in (19372692, 19372685);

no rows selected

The effective date for both showing in COLIN is 12:42pm on August 28th, but the date and time filed for one is 12:44 pm and the other is 12:46pm

COLIN does not allow more than one annual report to be filed for a specific calendar year, and their 2023 annual report had already been filed back in August of 2023.

**Comment by Mihai-QuickSilverDev** [comment]
@ozamani9gh

**Comment by schaturv18** [comment]
test

**Comment by ozamani9gh** [comment]
@thorwolpert is there anywhere in the logic, where this should not allow a company to process an A/R for the same year, my gut feeling is, they only process 1 annual report, but it gets inserted into COLIN twice (or sent over twice).  Any advice for Hanlun/Ethan to try and figure out if this was an isolated incident, or can this happen for any company filing in Business A/R

**Comment by dvdenis** [comment]
@ozamani9gh can you let the Home Team know if this is just a duplicate glitch, or if it was truly filed twice by the citizen?  Once we have confirmation that it truly is a straight up duplicate, we can have the second one deleted from the COLIN side to clean up the ledger.
Thank you.

**Comment by Maribeth-Wilson** [comment]
@ozamani9gh - to follow up on Sep 25th

**Comment by stevenc987** [comment]
@ozamani9gh @hanlunBCRegistries 

I tested my changed codes work well on Devl. If there is filing id in colin_event_ids, then it will skip processing the filing id so it wouldn't make duplicated row inserted in COLIN.

Please let me know when my codes can be moved to TEST

**Comment by stevenc987** [comment]
@ozamani9gh @mihailistov 

I checked the change is on TEST now. Please test it before we move it to PROD
