### ISSUE TITLE
Investigation:  BCROS invitation error BC1046656

### ISSUE THREAD

**Issue by ozamani9gh** [bcgov/business-ar#360]
OPS Related Ticket:

https://sbc-registries.atlassian.net/jira/servicedesk/projects/ITOPS/boards/5?quickFilter=6&selectedIssue=ITOPS-141651

BCROS invitation error BC1046656

Staff Full Name:    Kellie Horler

Supervisor's Name: Debbie Blyth

Date & Time of Issue: 2024-09-18  9:12AM

Detailed Description of Issue: user rec’d BCROS AR invitation, created account, however for over a month of trying – access is not possible. See screenshot below.

Troubleshooting and what has been tried: Sent clinet the AR CODE/reminderfor www.corporateonline.gov.bc.ca  

No need to contact client, as the old system allowed the filing. This ticket is to notify the BCROS team of the error when using a cell phone to file.

<img width="409" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1gxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b403fb3029a83fbc76b4736a2eb2ce9f5b7f7c15/image.png" alt="image.png" />

**Comment by Maribeth-Wilson** [comment]
@nsmenon8890 - fyi

**Comment by ozamani9gh** [comment]
@nsmenon8890 please let us know before Thursday if this is an issue with all mobile phone filings, or if you believe its just this one.

**Comment by ozamani9gh** [comment]
@nsmenon8890 i think this company tried to file before mobile capabilities were pushed into prod.   can we prove this... i believe our changes went in on the 19th of September.  if they tried before that, i dont think it would have worked.

if you are ok to close ticket.  please let me know so i can close ops ticket as well.

https://sbc-registries.atlassian.net/jira/servicedesk/projects/ITOPS/boards/5?quickFilter=6&selectedIssue=ITOPS-141651

**Comment by nsmenon8890** [comment]
Tested with iphone, not getting the internal server error. Tested with different cases.

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEVBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3fccd3fa612249616c6f8ea71ebf0529abebc3c4/IMG_3412.PNG" alt="IMG_3412.PNG" />

**Comment by nsmenon8890** [comment]
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNElBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ae3586ac246d66117f04aa8c7876ae5a9010a78/IMG_3413.PNG" alt="IMG_3413.PNG" />

**Comment by nsmenon8890** [comment]
Tested on with Production as well.

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFVBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47ebbe037c4e5b4e5d6e2d92ca9709e6096781a9/IMG_3415.PNG" alt="IMG_3415.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11d1dfb929c84077878c6530c6e1682829ce37e7/IMG_3414.PNG" alt="IMG_3414.PNG" />

**Comment by ozamani9gh** [comment]
Lets close this ticket and the OPS Ticket.

<img width="546" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHNBQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--65908c2a751c9643446f552aa6405b84b577af67/image.png" alt="image.png" />
