### ISSUE TITLE
Build Login Screen UI - Desktop -  that displays the multiple filings

### ISSUE THREAD

**Issue by EPortman** [bcgov/business-ar#368]
According to the Figma file, the following changes are required for the login screen. Please note that this ticket is for the desktop version only and does not include mobile updates.

- [ ] Add year to screen title. eg: File your 2024 BC Annual Report
- [ ] Update titles for both sections (Login to BC Registries, No account?)
- [ ] Add list of annual reports
  - [ ] Add static text: Reports must be filed from oldest to newest.
  - [ ] When a report is overdue, it has a red background
  - [ ] When a report is not overdue (within 60 days of anniversary date), it has a grey background. Text is aligned to the text within overdue reports (but does not display the triangle warning icon)
  - [ ] The 'Login to File Report' button is disabled if it is not the oldest annual report (user can only file reports in chronological order)
  - [ ] If the user selects 'Login to File Report' the user is directed to BC Services Card Login (same as current state)
- [ ] Read the overview button styling and text updates to "Annual Report Overview". Button links to the same place as current state.
- [ ] In the 'No account?' section, bullet point is removed

<img width="701" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1VFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e495be81a58e8ddf238302de61be1a252bfcd948/image.png" alt="image.png" />

**Figma Files**
[Login Screens](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2079-5402)  
[Flow](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2226-5790)

**Comment by nsmenon8890** [comment]
In chrome , it showing " Internal server error, please try again later or contact us for assistance."

<img width="1491" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUlyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f26bd4b8d2413d9254f377ffcb0ea8c06d0e484f/image.png" alt="image.png" />


But for Edge no error:

<img width="1497" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--627e947376c7c701e833df99ef3593aa0769965e/image.png" alt="image.png" />

**Comment by EPortman** [comment]
Interesting that it works in one browser and not the other. 

I did just try to look at the logs in google cloud and think this is the error that occurred.
<img width="1113" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlFyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b1b87c1ae8935990267bec6fc2f048ce26adacc/image.png" alt="image.png" />

<img width="1201" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55ad6af0408ebaef688566dbe7e1e77cba9ac9e2/image.png" alt="image.png" />


It seems like the business has a duplicate (`multiple rows found`). I will investigate and respond more when I confirm.

**Comment by nsmenon8890** [comment]
Incorporation Number should have a prefix : **BC**

**Comment by nsmenon8890** [comment]
UI -- Image missing
<img width="1153" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODR3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab70438c1d30d87ee30cb1c37fce2b8308a2aacb/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
Testing completed and process flow is working as expected.
Checked the CTST data base , last_ar_filed is mapping correctly.
Checked in COLIN and ledger is updating correctly.

**Comment by nsmenon8890** [comment]
Attaching screenshot from testing.

 <img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzB3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a7b8b4e3b86dc7997e12080e8aac0b2016d1f168/image.png" alt="image.png" />

<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL013Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5865fc27bb0bedccb72b5c1c0bc25d7e04127252/image.png" alt="image.png" />

 <img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1V3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ecfe7b68edd052fa5f224fd82db5555d3f5e3ea6/image.png" alt="image.png" />

<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1l3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55f3c4b463f6f56945edbb6348d60de14c424c2e/image.png" alt="image.png" />

 
<img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2N3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f89d790f940132fa20010c4d44200ea3b5b4a57c/image.png" alt="image.png" />

 <img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2d3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d2e3675973c72bf4e6937aa7dee56de0b0b41ae9/image.png" alt="image.png" />

 <img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2t3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7bb7e46cc2f7eebbea6394fb31ed846fb86830e6/image.png" alt="image.png" />


 <img width="975" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL293Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f9408bfcc638c4ed500acaebf5897ca7b217358e/image.png" alt="image.png" />
