### ISSUE TITLE
Build Success Screen UI that displays filings yet to complete

### ISSUE THREAD

**Issue by EPortman** [bcgov/business-ar#369]
According to the Figma file, the following changes are required for the success screen. Please note that this ticket is for the desktop version only and does not include mobile updates.

- [ ] Add year to title: "2023 Annual Report Complete"
- [ ] Add 'Your Receipt' title to first section
- [ ] Update styling of download receipt button
- [ ] Add 'File another Report' section
  - [ ] Add static text: Reports must be filed from oldest to newest.
  - [ ] When a report is overdue, it has a red background
  - [ ] When a report is not overdue (within 60 days of anniversary date), it has a grey background. Text is aligned to the text within overdue reports (but does not display the triangle warning icon)
  - [ ] The 'File Annual Report' button is disabled if it is not the oldest annual report (user can only file reports in chronological order)
  - [ ] Read the overview button styling and text updates to "Annual Report Overview". Button links to the same place as current state.
- [ ] Survey messaging is moved to the bottom section and external link icon has been added
- [ ] In bottom section there is a text update, "Service BC (SBC) Connect" has become "Service BC Connect"

<img width="701" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzBFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e28db0b997d20d291d9e07b7b902bde688b11ff1/image.png" alt="image.png" />

**Figma Files**
[Success Screens](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2248-10184)  
[Flow](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2226-5790)

**Comment by nsmenon8890** [comment]
Testing completed and working as expected. Attaching screenshot for reference.

<img width="1510" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmd4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--666a30a218b10059097709a0e694182cb338c304/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1128" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0l4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e8ea0490ce96b78f2fee6ef22563abcf9afa53d7/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="940" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2N4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2dd3517ca50e222955273e54f132462ded996d7f/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1294" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUF4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c80f0c438317ef2953a551bd96dc666788a565d1/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
1 Overdue, 1 Not Overdue

<img width="1350" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0V4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--60df9e8e43c38d6c96335cce0b17c4671b3b1b3f/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1417" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkUyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--68f6f57bc95eef2f88cd3019c4f08781fdb4a69e/image.png" alt="image.png" />

<img width="1340" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkkyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c37d314b0d8108f5219612a3b145574e526d1cf/image.png" alt="image.png" />

<img width="1436" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlEyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f40de20436a9d8e3d8636584210692382841ba9/image.png" alt="image.png" />

<img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmcyQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a35f429c5c56c7d4c58d66b810336f5e0ad3021/image.png" alt="image.png" />
