### ISSUE TITLE
Update Mobile UI screens for new Login and Success Screen

### ISSUE THREAD

**Issue by EPortman** [bcgov/business-ar#370]
The UI changes in tickets [368](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/368) and [369](https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/gh/bcgov/business-ar/369) require mobile UI updates. 
- [ ] Update mobile version of Login Screen
- [ ] Update mobile version of Success Screen

**Figma Files**
[Login Screens](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2079-5402)  
[Success Screens](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2248-10184)  
[Flow](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2226-5790)

**Comment by nsmenon8890** [comment]
Tested and working as expected.

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEJRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3705d647056f249d0b6043fdfc4de5c2f21eeb50/IMG_3478.PNG" alt="IMG_3478.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--009e608b2227f0e2908bf2621eec34c16a110a5c/IMG_3505.PNG" alt="IMG_3505.PNG" />

**Comment by nsmenon8890** [comment]
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEpRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b08c0a2174009919bbf285004e236f790b336f95/IMG_3480.PNG" alt="IMG_3480.PNG" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME5RQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc5c8a04f905393ef3347f617489ec50f321de7d/IMG_3481.PNG" alt="IMG_3481.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFJRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--576ef2e1a7fde4542acf97289f180db779431d1e/IMG_3482.PNG" alt="IMG_3482.PNG" />

**Comment by nsmenon8890** [comment]
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--61c04fcff11aef95bb8244b5eceea683fe6002bb/IMG_3483.PNG" alt="IMG_3483.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGRRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e757a6da029cc18dc8e077531195d4c4d097154/IMG_3484.PNG" alt="IMG_3484.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGxRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c10df3694636cecd4855c7fe48f190df6a5ce58e/IMG_3485.PNG" alt="IMG_3485.PNG" />


<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--212c44017f6e943912b5323a636449e3aa6fd61a/IMG_3486.PNG" alt="IMG_3486.PNG" />

**Comment by nsmenon8890** [comment]
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHhRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cffdc619ea514d2a6a061b4872ad684c13327819/IMG_3487.PNG" alt="IMG_3487.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDlRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9969880855d40538521b75b4f77939c81efc4f0a/IMG_3491.PNG" alt="IMG_3491.PNG" />


<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUZRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b01e5febff24bf121f4c73dcfbaa41a3c80c9d3/IMG_3492.PNG" alt="IMG_3492.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUpRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50ca88858aa716274eee078ac121c7160d8285e8/IMG_3493.PNG" alt="IMG_3493.PNG" />

**Comment by nsmenon8890** [comment]
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4804ec4da1bdcb6275f5aa7f4fea91356ab0d815/IMG_3494.jpg" alt="IMG_3494.jpg" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWRRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2f604e5ea7b85957b93090e3738dec294a3ddeb/IMG_3495.PNG" alt="IMG_3495.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddcd6042443b5686c7e07d0f310fe800a9d7273a/IMG_3496.PNG" alt="IMG_3496.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWxRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2a087e140fa481225934e9f4c3ad51457513a357/IMG_3497.PNG" alt="IMG_3497.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXRRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e5df55589a48bfa82d407eb27800d070b8213400/IMG_3498.PNG" alt="IMG_3498.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXhRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--795234ad76110cb9d6575ca78901e3a140cfaf7d/IMG_3499.PNG" alt="IMG_3499.PNG" />

**Comment by nsmenon8890** [comment]
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTFRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d1296c11d1d2adc36dae7a5e1b762965f9953ea0/IMG_3500.PNG" alt="IMG_3500.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTVRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--19573e0a32c6a23f8652e78ba043f20fcde7bfe3/IMG_3501.PNG" alt="IMG_3501.PNG" />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTlRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59fe39577a059c6e4aea8fb4fa737677e6121817/IMG_3502.PNG" alt="IMG_3502.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkJRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efb019fecdcf81e6946d3a2014fb07cc9757db56/IMG_3503.PNG" alt="IMG_3503.PNG" />

<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkZRQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f848a2d973a3e9e92d3a3cdbfa5ea89e57f8250/IMG_3504.PNG" alt="IMG_3504.PNG" />


<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk5RQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--feabdb75361ed37a4460ea6a31195058b2544f24/IMG_3505.PNG" alt="IMG_3505.PNG" />
