### ISSUE TITLE
New text to translate to French

### ISSUE THREAD

**Issue by EPortman** [bcgov/business-ar#371]
The new UI changes in tickets 368, 369, and 370 came along with text changes.  Use CHAT GPT
- [ ] Identify every difference in text and find the French translation
- [ ] Implement the above translations

**Figma Files**
[Flow](https://www.figma.com/design/UXwyiIiuerRmE9JeScSVn2/BAR?node-id=2024-3549&m=dev&focus-id=2226-5790)

**Comment by EPortman** [comment]
@ozamani9gh these translations have been added and verified to the figma files by Jaqueline. 

This ticket can be closed (QA for it can be done with the UI tickets).

**Comment by nsmenon8890** [comment]
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTVMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--778aa7f1a7c5246af79c129cbebb0192d5c029ab/image.png" alt="image.png" />

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTlMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4e9fa03db651b602a5fe15ea677e88cd7ea246ca/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlJMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a44fb0632e012f1a0108512f2e9b652743094a86/image.png" alt="image.png" />

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlZMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ed291fe9b985cd95de784129308469db126e83d/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
This screen is not converted to French:

<img width="1491" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkZQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb13ce7b07951e9e0f61de7ec2203e16df06b344/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnBQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ddbdc947bed19c63acfefc9ada95386c81114da1/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0JQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0160685b43863db781e4ad179f43b2b9203daed/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ZQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b472e8e339e3ca892900d69c03a037c85bc1d6a8/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a645ff66af4caeb3aea9c3c7d28353a9175ed801/image.png" alt="image.png" />
