### ISSUE TITLE
API Linting

### ISSUE THREAD

**Issue by EPortman** [bcgov/business-ar#394]
It seems as if it has been a long time since the API has been properly linted. 

I tried fixing this by adding `isort` (and fixing import related errors) and also running `poetry run black .` which fixed a couple hundred of these linting errors, but there are still hundreds left due to `pylint` and `flake8` that need to be fixed manually. 

**Example of a small amount of these errors**
<img width="921" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNU1iQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8e8327e64e5d2d5a87277de082c2041af462d88/image.png" alt="image.png" />

**Comment by hanlunBCRegistries** [comment]
No more linting errors now
