### ISSUE TITLE
Investigate issues with AUTH migration to GCPE

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#400]

**Comment by hanlunBCRegistries** [comment]
<img width="545" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0VrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7f6762b5ea7281920b41775a67e01a2efdbd600/image.png" alt="image.png" />
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0lrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3236d08f8e7c181c0296dde933108618aca0759d/image.png" alt="image.png" />
Potential mismatch on interface field names, talking with Travis to fix this

**Comment by nsmenon8890** [comment]
<img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME0yQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7f70e3f55a8d60d4c46d023b3ae4fe23d254c00/image.png" alt="image.png" />

Address is getting displayed for the respective accounts.
