### ISSUE TITLE
Email Receipts not working

### ISSUE THREAD

**Issue by EPortman** [bcgov/business-ar#421]
Email Receipts seem to not be getting sent when filings are synced with Colin. 

When the `process-paid-filings` job syncs a filing with Colin it is supposed to send an email with the receipt / confirmation. Here is the code for reference:
https://github.com/bcgov/business-ar/blob/main/jobs/process_paid_filings/src/process_paid_filings/job.py#L253

In the GCP logs the following error is appearing each time this happens:
```
DEFAULT 2024-10-10T17:50:22.512694Z Message: 'Error in send_notifications'
DEFAULT 2024-10-10T17:50:22.512702Z Arguments: (AttributeError("'tuple' object has no attribute 'get_data'"),)
DEFAULT 2024-10-10T17:50:22.512727Z [2024-10-10 17:50:22,514] ERROR in responses: AttributeError("'tuple' object has no attribute 'get_data'")
DEFAULT 2024-10-10T17:50:22.521199Z [2024-10-10 17:50:22,520] ERROR in job: Failed to send email for filing 420
```

These errors date back to September. There are over 400 errors in the logs, which is probably the same amount of filings done on this system indicating that this has never actually worked successfully.

**Comment by EPortman** [comment]
The name field has been fixed. 

<img width="744" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzlSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f153a847c36ca8f26daa68dd6f54878cb7b351fe/image.png" alt="image.png" />

The test account I am using has the name THOR.
<img width="297" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEpSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--248953cdbb1c670edf2077fd0f5b818d547a2d9b/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1896" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXBYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1a0551367ea08db6cb295a973dd3f03c86fe1cc/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1051" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTFYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2339abaddc9591cd5a01aec22dd5e0fbeb3a8136/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="931" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTlYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a73b4598b7d0a65a0b291c777a3727f424cba71/image.png" alt="image.png" />
