### ISSUE TITLE
INVESTIGATION: Fix Download Receipt issue

### ISSUE THREAD

**Issue by ozamani9gh** [bcgov/business-ar#427]
There is an issue with downloading the receipt.   please fix

<img width="669" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEJSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e45f88248b21506e6a961d3a4147a04ce0c4e006/image.png" alt="image.png" />

**Comment by Maribeth-Wilson** [comment]
@ozamani9gh - is this still an issue, or should this tix be closed?
