### ISSUE TITLE
Email UI issue when first creating an account

### ISSUE THREAD

**Issue by EPortman** [bcgov/business-ar#428]
## This is only a problem when creating a new account

When I go into the UI and sign in and then create a new account with an email and phone number, the `account-store` does not get updated properly. This is what the store looks like after creating a new account:
<img width="697" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDlSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad1d9c21a23d13b1e94d6043f3f386df68a458f9/image.png" alt="image.png" />

Notice that the contacts is an empty array, when this happens the UI thinks there is no email available when in fact there is:
<img width="700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUJSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b030d6092d1b99082cea849ce48ac10f2b11ad39/image.png" alt="image.png" />

The store gets updated properly when choosing an existing account. For example if I log out and then log into the previously created account the store is correct.
<img width="699" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVJSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e9009ca0392b9b84f1ddac3be46d8674fc72614/image.png" alt="image.png" />

This means the UI is able to pick it up and work properly.
<img width="701" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVpSQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57d352445c88d6a4928ae93223a52ce40a3b4fa1/image.png" alt="image.png" />

**It is important to note that in both cases the email is still sent to the user, this is just a UI Issue**

**Comment by nsmenon8890** [comment]
Testing completed.

<img width="1331" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG1CQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2f6b524cc41c9ae4bd4512900f46d03b2dc4154/image.png" alt="image.png" />

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHFCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4bfa89ed0ddb59bf20be617b53ef0f0e39117eeb/image.png" alt="image.png" />

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHlCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94423b3ed2a1bfd6283d24ca6117abee06ae153f/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDJCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e18eed29add5f071c4c1632922829fa4f8af7f8/image.png" alt="image.png" />

**Comment by hanlunBCRegistries** [comment]
@nsmenon8890 Would you try clock Submit&Pay to see if the email is gonna display

**Comment by nsmenon8890** [comment]
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMCtCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--149e0693c4aa1c9a098b89b5cc8f45b73731c3e0/image.png" alt="image.png" />

**Comment by hanlunBCRegistries** [comment]
Great! Thanks a lot Neeraja @nsmenon8890
