### ISSUE TITLE
INVESTIGATE:  Error in process_paid_filings Job to Generate pdfs Due to Missing Fields in Template Variables (Production)

### ISSUE THREAD

**Issue by hanlunBCRegistries** [bcgov/business-ar#431]
Encountered errors in the process_paid_filings job in production. The issue seems to stem from a missing registeredOffice value in the template variables, which is causing the report API to throw a jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'registeredOffice'.

I believe this issue is specific to production, as I’m unable to reproduce it in the dev or test environments, where no errors are occurring.

The error in production is:
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'registeredOffice'
This error seems to be linked to the following line in the code, where the REPORT_SVC_URL API is called:
https://github.com/bcgov/business-ar/blob/d5a5b909b666dc4f74fd70d952bee331945281f9/api/src/business_ar_api/services/report_service.py#L49

Similar Errors: In dev, there was a different error:
jinja2.exceptions.UndefinedError: 'effective_date' is undefined
This one I was able to track down, as effective_date was missing from the template variables, but in production, it seems to be the registeredOffice value.

**Comment by nsmenon8890** [comment]
Tested and confirmed.

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMktHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb5e036286a46cd5a5d293b4809b3180fa872891/image.png" alt="image.png" />

**Comment by nsmenon8890** [comment]
[Receipt.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlNHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--300a81cdafe5dcb6c890470c6d1ab3d24cdf29cb/Receipt.pdf)

**Comment by nsmenon8890** [comment]
[2024 Annual Report.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMldHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db22378dc50db40032b2d37d4e4f229f0dd595ea/2024%20Annual%20Report.pdf)
