### ISSUE TITLE
Update BAR email template to change the' questions and support' contact to Maximus

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#434]
Update the BAR email with the following updated contact info:

**Questions & Support?** Contact the BC Registries help desk at bcrossupport@gov.bc.ca or 1-877-370-1033 from 8:30 am to 4:30 pm Pacific time, Monday to Friday, except statutory holidays.

Thank you, 

BC Registries and Digital Services
Service BC | Ministry of Citizens’ Services
Access to government services made easy

**Comment by nsmenon8890** [comment]
Tested and confirmed.
