### ISSUE TITLE
BAR filing- The citizen is not able to see the receipt on the COLIN legder when they file the Annual Report in BCROS

### ISSUE THREAD

**Issue by nsmenon8890** [bcgov/business-ar#450]
BAR filing- The citizen is not able to see the receipt on the COLIN legder when they file the Annual Report in BCROS

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZMQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7998d4e3b4552465f7fa2b5d41aecd302a06c736/image.png" alt="image.png" />

**Comment by hanlunBCRegistries** [comment]
Currently it's included in the email receipt, if we want to offer download receipt feature it's better to do on BAR side.

**Comment by Maribeth-Wilson** [comment]
@nsmenon8890 - is this tix still required?

**Comment by nsmenon8890** [comment]
@Maribeth-Wilson No, I will close the tix. Please let the respective team from helpdesk know that we will not be able to see the receipt in COLIN side.
