### ISSUE TITLE
BAR Reminder - ERROR - BC0806860

### ISSUE THREAD

**Issue by LANHALL2** [bcgov/business-ar#454]
This is just an FYI - to investigate later. 

On October 25, 2024 Apple Tree Consulting Inc. received an annual report reminder to file it's company annual report on or after October 27, 2024. 

On October 28, 2024 the citizen attempted to file the report and received a payment error. 

<img width="640" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkNQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0d33bab28f84799fd81fa29e997efa4a21fa79f2/image.png" alt="image.png" />

The citizen had attempted to file it again and received the same error message. 

On October 29, 2024 citizen had emailed BCOL Help and spoke with Andy, Andy sent the inquiry to the engagement team inbox. I found that although the company attempted to file on the 28th and was trying again on the 29th with Andy, Corporate Online shows that we received the annual report on October 28th at 11:42am. 

<img width="1471" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNktQQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a56f3c231a54baa080aa5bc66e1ba187e092399/image.png" alt="image.png" />

At the end of the day, the report has been received however, unsure why it was providing a payment failed error although, it filed. 

Perhaps, the issue with the payment issues were happening prior to it being reported. 

@Maribeth-Wilson

**Comment by Maribeth-Wilson** [comment]
@PCC199 - this is for your fyi only
