### ISSUE TITLE
BAR _ Mismatch in Filing Numbers between BI Dashboard and CPRD Production Database

### ISSUE THREAD

**Issue by nsmenon8890** [bcgov/business-ar#458]
A discrepancy was observed in the filing numbers displayed on the BI dashboard when compared with the CPRD production database. 

For Instance, the BI dashboard shows:
For Nov 5th:

COLIN filings: 23
BCROS filings: 15

On checking CPRD,  I can see more filing completed on Nov 5th.
BCROS number is correct, I have doubt in COLIN numbers only.
Could you please investigate and resolve the discrepancy?

**Comment by vikas-gov** [comment]
How many more filings and are these related to invitations sent or total filings?

**Comment by vikas-gov** [comment]
Based on latest conversation on this topic, this is not a bug.
