### ISSUE TITLE
Investigate: BCOL HD reported that they have received calls that users are not receiving receipts

### ISSUE THREAD

**Issue by Maribeth-Wilson** [bcgov/business-ar#460]

**Comment by hanlunBCRegistries** [comment]
In auth.users table they don't have emails setup there, and they don't have a contacts created, that's notify services cannot send out receipts

**Comment by PCC199** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Annual-Report-Filing-for-Corporations-661483a4f4f833001637ec44/issues/bcgov/business-ar/460?planning-poker) with Zenhub @hanlunBCRegistries

**Comment by hanlunBCRegistries** [comment]
Users could add their email through BC registries dashboard: <img width="1193" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9EQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6a699584349176c3d9fb70697a52df03429067a/image.png" alt="image.png" />
