### ISSUE TITLE
Fix Affiliation Creation Logic for Entities Requiring Passcode

### ISSUE THREAD

**Issue by hanlunBCRegistries** [bcgov/business-ar#467]
# Description:
Currently, when creating an affiliation, the request fails if the entity requires a passcode and the user does not provide one. This affects users who are not staff, as the current system does not prompt for a passcode. Without a valid passcode, the request is rejected, preventing users from proceeding.

## Steps to Reproduce:

Attempt to create an affiliation for an entity that requires a passcode.
Do not provide the passcode in the request.
Observe that the request is rejected.

## Proposed Solution:

Implement a check in the frontend/backend to verify if the entity requires a passcode.
Use a GET call to check for the passcode requirement before creating the affiliation.
If a passcode is required, prompt the user to enter it during the affiliation process.
Add a screen or modal for passcode entry.
Alternatively, instruct users to create the affiliation through the business dashboard if there is a passcode exist

**Comment by hanlunBCRegistries** [comment]
@nsmenon8890 This ticket is ready to test, please let me know if you need more detail

**Comment by nsmenon8890** [comment]
Testing completed and working as expected.

<img width="1891" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN25VQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--441f3f5bb62ee9196608655c9b7a08d1a467ff68/image.png" alt="image.png" />

<img width="1557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ZVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2c1c20e4496349d051f89b3ca370e497b198eab/image.png" alt="image.png" />

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzNVQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--28687071d2c7981f7398f9fb9fbdf893f9d861b9/image.png" alt="image.png" />

<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy9VQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ba9a770b444f43f1289eec4db9cd0cb29128aae/image.png" alt="image.png" />
