### ISSUE TITLE
Activity Report

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/business-ar#95]
## Determine:
- Streamlit; or
- Notebook and Google Sheets
## Track:
- Completed ARs
- Completed Accounts
- Abandoned ARs
- Abandoned Accounts

**Comment by thorwolpert** [comment]
Review with @trishreimer to determine stack

**Comment by trishreimer** [comment]
The activity report would be helpful so we can report out on our KPI's:
- # of corps to transition / accounts setup
- #of AR's filed in the new BizReg 

Can we make this a quick and easy real time report that is accessible to others?

**Comment by thorwolpert** [comment]
sure, realtime would lean more towards streamlit or a some Nuxt pages

**Comment by trishreimer** [comment]
I'm hoping to get this in place for the next iteration as I'd like to send the next round to about 50 corps.
